name: Deploy Dev on Self-hosted EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start Vite Dev  Server with PM2
        run: |
          # Start or restart Vite dev server using PM2
          pm2 restart "cicd"
          pm2 save

          
